version: 2
jobs:
  build:
    working_directory: ~/git-chat-server
    docker:
      - image: node:8
      - image: mongo:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: yarn --non-interactive --no-progress
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - run:
          name: prepare-env
          command: envsubst < ./.env.template > .env
      - run:
          name: test
          command: yarn run test
      - store_artifacts:
          path: coverage
          prefix: coverage
