version: 2
jobs:
  build:
    working_directory: ~/git-chat-server

    docker:
      - image: node:8
      - image: mongo:latest

    steps:
      - checkout

      - run:
          name: Prepare environment
          command: |
            apt-get update -qq
            apt-get install -y --force-yes gettext-base
            envsubst < ./.env.template > .env

      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Install NPM packages
          command: yarn --non-interactive --no-progress

      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - run:
          name: LS
          command: |
            echo '----------------------------'
            ls -la
            echo '----------------------------'
            ls -la ~/
            echo '----------------------------'
            ls -la ~/git-chat-server
            echo '----------------------------'
            ls -la ./node_modules/.bin
            echo '----------------------------'

      - run:
          name: Test application
          command: ~/git-chat-server/node_modules/.bin/jest --coverage --forceExit --runInBand

      - run:
          name: Remove ENV file
          command: rm .env

      - store_artifacts:
          path: coverage
          prefix: coverage
